management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true

spring:
  application:
    name: azure-demo


info:
  application:
    name: Azure Demo
    description: A demo application for Azure integration
    author: Professor Husnain
    version: '@project.version@'
